### ISSUE TITLE
API updates Feb 2016

### ISSUE THREAD

**Issue by janeczku** [JamesClonk/vultr#12]
`/v1/server/list`

New field: `server_state`
more detailed status of: none | locked | installingbooting | isomounting | ok

Deprecated fields:  `v6_network`, `v6_main_ip`, and `v6_network_size`
Replaced by: `v6_networks` JSON object array

`api-rate-limit` upped from 1/sec to 2/sec :laughing: WOW

Whenever you have some spare time... :smile:

**Comment by JamesClonk** [comment]
Thanks, added server_state and v6_networks to the library.
:+1:
