### ISSUE TITLE
For 'vultr server create' make the -o flag optional if --snapshot is defined

### ISSUE THREAD

**Issue by martindehh** [JamesClonk/vultr#27]
There is a discrepancy between the Webinterface/API and this CLI; When you select a new machine to be deployed from a snapshot you don't have to provide the OS definition, but in the CLI you have to.

Example:
Create a CoreOS Stable Machine
Upgrade CoreOS to the Beta Channel
Make s Snapshot of the Server
When trying to create a Server with: vultr server create -n $SERVER_NAME -r $REGION -p $PLAN --snapshot="$SNAPSHOT" it points out that you have to specify -o
When trying to get a CoreOS Beta with: vultr server create -n $SERVER_NAME -r $REGION -p $PLAN --snapshot="$SNAPSHOT" -o 179  then /etc/coreos/update.conf contains GROUP=stable which is not desired
You can do this properly with the Vultr Webinterface and API.

**Comment by JamesClonk** [comment]
You have to use the **snapshot** type OS (id 164) when creating servers with snapshots. If you use any other id / type then the Vultr API unfortunately ignores the snapshot parameter, as OSID takes precedence.
(See documentation under https://www.vultr.com/api/, section `/v1/server/create`, `SNAPSHOTID`)

```
[jamesclonk:vultr (master)*]$ vultr os
OSID    NAME                    ARCH    FAMILY          WINDOWS
...
164     Snapshot                x64     snapshot        false
```

```
[jamesclonk:vultr (master)*]$ vultr server create -n snaptest -o=164 --snapshot=b90585657634f                  
Virtual machine created

SUBID           NAME       DCID    VPSPLANID       OSID
6135289         snaptest   1       29              164
```

**Comment by martindehh** [comment]
Thanks for the respond.
Your suggested workaround is working very good.

I see that it is impractical to set o=164 automatically when --snapshot is defined, because of how ServerOptions is handled at the moment. Maybe this could go into the README so other people find this useful information.

Thank You
