### ISSUE TITLE
incorporate /v1/app/list?

### ISSUE THREAD

**Issue by jonspraggins** [JamesClonk/vultr#30]
Example Request:
curl https://api.vultr.com/v1/app/list

Example Response:
{
    "1": {
        "APPID": "1",
        "name": "LEMP",
        "short_name": "lemp",
        "deploy_name": "LEMP on CentOS 6 x64",
        "surcharge": 0
    },
    "2": {
        "APPID": "2",
        "name": "WordPress",
        "short_name": "wordpress",
        "deploy_name": "WordPress on CentOS 6 x64",
        "surcharge": 0
    }
}

**Comment by JamesClonk** [comment]
should be there now, together with output sorting. see https://github.com/JamesClonk/vultr/issues/31

**Comment by elricsfate** [comment]
Excellent, thank you!
