### ISSUE TITLE
Sort output of Vultr Plugin (Output currently unordered)

### ISSUE THREAD

**Issue by elricsfate** [JamesClonk/vultr#31]
As mentioned in title. Sorting by price seems most logical. 

@JamesClonk Additionally, is this repo still maintained? If not, I will likely create a fork.

**Comment by JamesClonk** [comment]
Hmm, sure. Sounds good, I'll find some time to do that on the weekend.

Yes, I still do maintain this repo, merge the occasional PR etc.. It's just that I don't actively add any new features anymore unless there's breaking API changes on Vultr side, as for my purposes the project is stable / done.

**Comment by elricsfate** [comment]
@JamesClonk 

Thanks a ton! I may see about submitting a PR or two myself then for things such as the applications feature (Which I don't believe is integrated). I'd like to integrate that into my terraform provider and it's based on this. 

Another note: it would appear the output of everything is currently unsorted so I will change the title.

**Comment by JamesClonk** [comment]
ok, I added various degrees of sorting to all list functions.

Also added the basics of the applications feature, though I didn't have time to test it thoroughly.

**Comment by elricsfate** [comment]
Excellent, thank you!

**Comment by JamesClonk** [comment]
I guess this can be closed now. 😄
