### ISSUE TITLE
Show used bandwidth in summary

### ISSUE THREAD

**Issue by noplanman** [JamesClonk/vultr#33]
When showing all servers, it would be nice if the used bandwidth for each would be listed too.

So instead of just showing the number that the instance allows:
```
BANDWIDTH
1000
```
show the used bandwidth too:
```
BANDWIDTH
40.2/1000
```

The field should offer enough space to display this.

**Comment by JamesClonk** [comment]
Ok!
👍

**Comment by noplanman** [comment]
Nice, thanks 😃 

Any idea how long it takes for the new version to be on brew?

**Comment by JamesClonk** [comment]
From what I remember homebrew tracks the tagged releases of this gitrepo. So it probably doesn't get picket up until the next release version. 
I think it's possible to specify the latest master / commit though somehow when installing.
Hmm, ah yes, it looks like `--HEAD` would do that.
