### ISSUE TITLE
add support for managing the reverse dns

### ISSUE THREAD

**Issue by rgl** [JamesClonk/vultr#4]
as described at:

* https://www.vultr.com/api/#server_reverse_set_ipv4
* https://www.vultr.com/api/#server_reverse_set_ipv6
* https://www.vultr.com/api/#server_reverse_list_ipv6
* https://www.vultr.com/api/#server_reverse_delete_ipv6

BTW, I'm trying to create a terraform provider with your library at https://github.com/rgl/terraform-provider-vultr, feel free to join :-)

**Comment by JamesClonk** [comment]
I just added IP4/6 and reverse DNS to the latest version.
You could check it out to see if it works for you.
