### ISSUE TITLE
Cannot customize hostname

### ISSUE THREAD

**Issue by fefas** [JamesClonk/vultr#44]
I am getting the error message `Server add failed: Invalid hostname` for any hostname name I use for the argument `--hostname`.

**Comment by JamesClonk** [comment]
Hmm, what exactly where the arguments you tried with?
I just tested it and it worked fine creating a new machine with the specified hostname.

**Comment by fefas** [comment]
I tired many like: `xyz-a-1`, `test`, `acme.com`, `acme`. but I had no time to test it again..

**Comment by fefas** [comment]
I will close this issue because I am not using the vultr service anymore.. @JamesClonk.. thank you for your support
