### ISSUE TITLE
`pending_charges` has changed from `float64` to `string`

### ISSUE THREAD

**Issue by vimagick** [JamesClonk/vultr#5]
vultr.com updated theirs API, several commands doesn't work anymore.

```
$ vultr servers
2015/07/07 19:48:07 json: cannot unmarshal string into Go value of type float64

$ vultr server show 12345
2015/07/07 19:52:49 json: cannot unmarshal string into Go value of type float64
```

**Comment by JamesClonk** [comment]
I pushed the necessary changes to the library yesterday, but I still have to create binary release for v1.4. Will do that on the weekend.

**Comment by vimagick** [comment]
:+1:

**Comment by JamesClonk** [comment]
OK, new release is up.
I hope I got all the fields that changed in the API.

It's a bit unfortunate that this isn't documented clearly on their side. 
I noticed that some fields change types from numbers to strings and vice-versa on a whim.

**Comment by vimagick** [comment]
Great! Thank you for your hard work. :smile:

**Comment by janeczku** [comment]
@JamesClonk I had been getting `json: cannot unmarshal string into Go value of type float64` when using the `GetServer` method. I guess commit https://github.com/JamesClonk/vultr/commit/aacf00e720729b122af94716ebe70e467dbee96b fixes that?

**Comment by vimagick** [comment]
solved
