### ISSUE TITLE
Please don't disable SSH host key checking unconditionally

### ISSUE THREAD

**Issue by gertvdijk** [JamesClonk/vultr#59]
https://github.com/JamesClonk/vultr/blob/e2c62e513c91feeb409764a8e6ab42e8ecc65df7/cmd/commands_ssh_unix.go#L15-L16

These two lines undermine the security of SSH significantly, I believe.

* Existing known host keys aren't checked.
* Host key verification in itself isn't performed, really.

Potential risk: man in the middle attacks, or, accidentally connecting to the wrong server (e.g. stale information, new IP, load balanced).

I would strongly suggest to leave it up to the user to accept/verify unknown host keys and to use default known hosts file, i.e. remove the two lines. It would be great if the public key generated for each Vultr instance would be exposed by Vultr's API, but it isn't, I believe, so there's not much that you can do in a client library.

(I did not go through the Windows code path here, possibly also affected.)

**Comment by JamesClonk** [comment]
Well, I always found it rather convenient not to be bothered by it. But I guess you're right, it should be up to the user / his ssh-config.
I commented it out. 👍
