### ISSUE TITLE
App Info Feature

### ISSUE THREAD

**Issue by anomalyze** [JamesClonk/vultr#62]
The Vultr API has a 'get_app_info' request for finding out the details of the application installed. at https://www.vultr.com/api/#server_get_app_info I couldn't find any feature related to this within the Vultr CLI.

Use case:
I spin up a OpenVPN server, and the login credentials (different to the VPS credentials) are detailed within this API call.

**Comment by JamesClonk** [comment]
@anomalyze Sorry for the long delay, I've been a bit busy the last few weeks.
I had planned to put it on my todo list, but saw that you already provided the feature with this pull request https://github.com/JamesClonk/vultr/pull/63 now. Thanks for your work! 😄 👍
