### ISSUE TITLE
This project's license is MIT, but has a dependency which is LGPLv3

### ISSUE THREAD

**Issue by yinonavraham** [JamesClonk/vultr#68]
Although this project is licensed as MIT (which is awesome, thanks!), it uses at least one dependency which has a more limiting license - LGPLv3: https://github.com/juju/ratelimit
It is highly recommended to switch to a different library which gives the functionality you need but has a friendlier license, or write it on your own...

**Comment by JamesClonk** [comment]
Thanks for the hint! 👍 
I've switched it to golang.org/x/time/rate now.
