### ISSUE TITLE
Creating server from snapshot, hostname argument ignored

### ISSUE THREAD

**Issue by Niek** [JamesClonk/vultr#69]
When creating a new server from a snapshot (with ``--os=164 --snapshot=ID``), the ``--hostname`` parameter seems to be ignored. The newly created server always gets the same hostname as the server where the snapshot was generated from.

Not sure if this is an issue with the CLI or the Vultr API.

**Comment by grahamking** [comment]
It looks like a problem with the Vultr API. I tried directly with `curl` and hit the same problem, the hostname was `vultr.guest` rather than the `--data "hostname=my.example.com"` I passed to curl.

**Comment by grahamking** [comment]
Vultr has an undocumented metadata query to fetch the userdata (I found it [in this comment](https://discuss.vultr.com/discussion/comment/5630/#Comment_5630)). What we ended up doing is pass the hostname as userdata, then run a script on boot to set the hostname to that:

```
HNAME=$(curl -m 5 http://169.254.169.254/user-data/user-data)
if [ -z "$HNAME" ]; then
        echo "Missing user-data, hostname not set."
        exit
fi
hostnamectl set-hostname ${HNAME}
sed -i "s/vultr.guest/${HNAME}/g" /etc/hosts
touch /var/lock/vultr-set-hostname.lock # systemd ConditionPathExists checks this
echo "Success. Hostname set to ${HNAME}"
```

In curl to pass hostname as userdata we do: `--data "userdata=$(echo hostname.example.com | base64)"`. Using the `vultr` CLI you'd have to write that to a file, but it base64 encodes it for you.

I think Digital Ocean uses `cloud-init` to make this work for us. It would be great if Vultr could do something similar. Either way I think this issue can be closed, nothing the CLI can do.

**Comment by Niek** [comment]
OK, I'm closing this as it's indeed an issue with the Vultr API. I have reached out to them to make them aware of the issue, hopefully it will be fixed soon.

**Comment by grahamking** [comment]
@Niek The hostname in the metadata (`/v1/hostname`) is `vultr.guest` on my machines. This goes back to your original issue, Vultr ignored the `--hostname` parameter, so it can't later tell us via the metadata what the correct hostname should be.

**Comment by Niek** [comment]
@grahamking Hmm strange, in my case the hostname provided with ``--hostname`` is not applied to the OS, but still available in the metadata.
