### ISSUE TITLE
Feature request: make vultr use proxy env vars

### ISSUE THREAD

**Issue by tddschn** [JamesClonk/vultr#77]
I installed `vultr` with `brew install vultr` on mac and it doesn't seem to read proxy env vars (http_proxy or all_proxy):

```bash
$ vultr version
Client version:         2.0.1
Vultr API endpoint:     https://api.vultr.com/
Vultr API version:      v1
OS/Arch (client):       darwin/amd64
Go version:             go1.13.1

$ vultr info
2020/08/07 **:35:57 Your IP (**********) is not authorized to use this API key
```
I rely on proxies to access the internet behind a firewall - it would be great if `vultr` supports http or socks5 proxy!

**Comment by JamesClonk** [comment]
@tddschn I've added a check for `http_proxy` env var: https://github.com/JamesClonk/vultr/commit/2656ceb96c75438830c5224196c565c9abf248c3
If you'll install/build the latest from source it should work.

**Comment by tddschn** [comment]
Thank you for the fix!!
