### ISSUE TITLE
Time for new release?

### ISSUE THREAD

**Issue by poffe** [JamesClonk/vultr#82]
Seems like master builds just fine. So is it time for a new release? This would be very much appreciated to enable Homebrew building using go 1.16 in the easiest possible way. It's the addition of go modules that's key.

To my novice eyes the only thing maybe missing for a release might be an updated README, or am I totally off here?

**Comment by JamesClonk** [comment]
I've created a new release, hope this helps.

**Comment by poffe** [comment]
Oh, thank you very much. That helps!
