### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by sammcj** [JamesClonk/vultr#9]
It would be great if this could be added to homebrew!

This would make it easy to:

- Install.
- Keep up to date.

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by JamesClonk** [comment]
I created a PR for it to be added to homebrew: https://github.com/Homebrew/homebrew/pull/45987
:smiley:
